/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the current user's weekly availability. */
        get: operations["AvailabilityRoutes_read"];
        /** @description Create or replace the current user's availability. */
        put: operations["AvailabilityRoutes_upsert"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/book/{username}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a booking for a free slot. */
        post: operations["Book_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/book/{username}/{slug}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List free time slots for a given event type. */
        get: operations["Book_slots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings/{bookingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get booking details by ID. */
        get: operations["Bookings_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all event types for the current user. */
        get: operations["EventTypes_list"];
        put?: never;
        /** @description Create a new event type. */
        post: operations["EventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types/{eventTypeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get a single event type by ID. */
        get: operations["EventTypes_read"];
        put?: never;
        post?: never;
        /** @description Delete an event type. */
        delete: operations["EventTypes_delete"];
        options?: never;
        head?: never;
        /** @description Update an existing event type. */
        patch: operations["EventTypes_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Weekly availability schedule for a host. */
        Availability: {
            /** Format: int64 */
            readonly id: number;
            /** @description The user this availability belongs to. */
            readonly userId: string;
            /** @description JSON array of time windows per day of week. */
            slots: components["schemas"]["AvailabilitySlot"][];
        };
        /** @description A single time window on a specific day of the week. */
        AvailabilitySlot: {
            /**
             * Format: int64
             * @description 1 = Monday … 7 = Sunday.
             */
            dayOfWeek: number;
            /** @description Start time in HH:mm format (host's timezone). */
            start: string;
            /** @description End time in HH:mm format (host's timezone). */
            end: string;
        };
        AvailabilityUpdate: {
            slots: components["schemas"]["AvailabilitySlot"][];
        };
        /** @description A booking made by a guest for a specific event type. */
        Booking: {
            /** Format: int64 */
            readonly id: number;
            /**
             * Format: int64
             * @description The event type that was booked.
             */
            eventTypeId: number;
            eventType?: components["schemas"]["EventType"];
            /** @description Guest's name. */
            guestName: string;
            /**
             * Format: email
             * @description Guest's email.
             */
            guestEmail: string;
            /**
             * Format: date-time
             * @description Booking start time in UTC.
             */
            startTime: string;
            /**
             * Format: date-time
             * @description Booking end time in UTC.
             */
            endTime: string;
            /** @description Host's timezone at the time of booking. */
            timezone: string;
            /** Format: date-time */
            readonly createdAt: string;
        };
        BookingCreate: {
            /**
             * Format: date-time
             * @description Slot start time in UTC.
             */
            startTime: string;
            /** @description Guest's full name. */
            guestName: string;
            /**
             * Format: email
             * @description Guest's email address.
             */
            guestEmail: string;
        };
        /** @description A meeting template created by the host. */
        EventType: {
            /** Format: int64 */
            readonly id: number;
            /** @description Short title (e.g. "30 Minute Consultation"). */
            title: string;
            /** @description URL-friendly identifier, unique per user (e.g. "30min"). */
            slug: string;
            /** @description Optional longer description. */
            description?: string;
            /**
             * Format: int64
             * @description Meeting duration in minutes.
             */
            duration: number;
            /** @description The user who owns this event type. */
            readonly userId: string;
        };
        EventTypeCreate: {
            title: string;
            slug: string;
            description?: string;
            /** Format: int64 */
            duration: number;
        };
        EventTypeUpdate: {
            title?: string;
            description?: string;
            /** Format: int64 */
            duration?: number;
        };
        SlotsResponse: {
            eventType: components["schemas"]["EventType"];
            timezone: string;
            slots: components["schemas"]["TimeSlot"][];
        };
        /** @description A single free time slot returned by the slots endpoint. */
        TimeSlot: {
            /**
             * Format: date-time
             * @description Slot start in UTC.
             */
            start: string;
            /**
             * Format: date-time
             * @description Slot end in UTC.
             */
            end: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AvailabilityRoutes_read: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Availability"];
                };
            };
        };
    };
    AvailabilityRoutes_upsert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvailabilityUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Availability"];
                };
            };
        };
    };
    Book_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
        };
    };
    Book_slots: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path: {
                username: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotsResponse"];
                };
            };
        };
    };
    Bookings_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bookingId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
        };
    };
    EventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    EventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
        };
    };
    EventTypes_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
        };
    };
    EventTypes_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventTypes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventTypeId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
        };
    };
}
